# This workflow will build a Java project with Ant
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-java-with-ant

name: Java CI

on:
  push:
    branches: [ "5.0.3-class-cast-exception" ]
  pull_request:
    branches: [ "5.0.3-class-cast-exception" ]

jobs:
  build:

    runs-on: ubuntu-latest
    continue-on-error: true
    steps:
    - uses: actions/checkout@v4
    - name: Build with Ant
      run: ant -noinput -buildfile build.xml
    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'
      continue-on-error: true
    - name: Build with Ant
      run: ant -noinput -buildfile build.xml
    - name: Set up JDK 21
      uses: actions/setup-java@v4
      with:
        java-version: '21'
        distribution: 'temurin'
      continue-on-error: true
    - name: Build with Ant
      run: ant -noinput -buildfile build.xml
